### PR TITLE
Vercel migration: 20mins

### PR DESCRIPTION
**Pull request by paul-sachs**
Fixes OPS-94

### CODE REVIEW

**Comment by timostamm** [comment]
Are we switching to ease some pain points with Netlify? Would be nice to have some info on this PR for posterity :)

**Comment by paul-sachs** [comment]
@timostamm will have more details when I merge this but the short version is that Netlify increased their prices 10x. This is me messing with switching to vercel instead.

**Review by timostamm — APPROVED** [review]
> Netlify increased their prices 10x

:panic_stamp:  :grinning:

**Comment by paul-sachs** [comment]
Fixes OPS-94

**Pull request merged**
